# Generated by Django 3.2.7 on 2022-02-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant_bot', '0004_auto_20220207_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='getlistfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
